In [2]:
import torch

# Example logits and targets
logits = torch.tensor([[0.2, 0.5, 0.3], [0.8, 0.1, 0.1]])  # Shape: (batch_size, num_classes)
targets = torch.tensor([3, 1])  # Shape: (batch_size,)

# Obtain predicted labels
predicted_labels = torch.argmax(logits, dim=1)+1  # Shape: (batch_size,)

# Compare predicted labels with targets
correct_predictions = predicted_labels.eq(targets)  # Shape: (batch_size,)

# Calculate accuracy
accuracy = correct_predictions.float().mean().item()

print(f"Accuracy: {accuracy}")

Accuracy: 0.5


In [2]:
import numpy as np
my_list = [1,2,3,4,5]  # Original list
given_order = np.random.permutation(my_list)  # Given order

# Sort the list based on the given order
reordered_list = sorted(my_list, key=lambda x: list(given_order).index(x))

print(reordered_list)

[4, 1, 2, 3, 5]


In [1]:
import torch

import torch.nn as nn

class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.fc = nn.Linear(10, 5)

model = MyModel()

# Access the weight parameter of the linear layer (nn.Linear)
weight = model.fc.weight
print(weight)

Parameter containing:
tensor([[-0.0442, -0.1917, -0.1996,  0.1414, -0.2238,  0.1140,  0.2459, -0.2671,
         -0.0797,  0.1882],
        [ 0.2756,  0.1624, -0.1246, -0.0331, -0.0449, -0.1547,  0.2997,  0.1138,
          0.2332, -0.1224],
        [ 0.0642,  0.0949,  0.2816, -0.1502, -0.1540, -0.2988,  0.1902,  0.0542,
          0.1674, -0.1483],
        [ 0.0230,  0.0227, -0.2840,  0.2945,  0.2882, -0.1243,  0.3031,  0.0629,
         -0.1000,  0.0195],
        [ 0.0152, -0.1481, -0.1616,  0.1699,  0.1351,  0.1552, -0.1180,  0.2252,
         -0.1262, -0.1113]], requires_grad=True)


In [5]:
import torch

# Create a tensor
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Perform circular shift along the first dimension (rows)
shifted_tensor = torch.roll(tensor, shifts=-1, dims=1)

print(shifted_tensor)
print(tensor)

tensor([[2, 3, 1],
        [5, 6, 4],
        [8, 9, 7]])
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])


In [2]:
import torch
print(torch.cuda.is_available())

False


In [6]:
def is_valid(board, row, col):
    for i in range(col):
        if board[row][i] == 1:
            return False

    for i, j in zip(range(row, -1, -1), range(col, -1, -1)):
        if board[i][j] == 1:
            return False

    for i, j in zip(range(row, len(board), 1), range(col, -1, -1)):
        if board[i][j] == 1:
            return False

    return True

def solve_n_queens(board, col):
    if col >= len(board):
        return True

    for i in range(len(board)):
        if is_valid(board, i, col):
            board[i][col] = 1

            if solve_n_queens(board, col + 1):
                return True

            board[i][col] = 0

    return False

def n_queens(n):
    board = [[0]*n for _ in range(n)]

    if not solve_n_queens(board, 0):
        print("Solution does not exist.")
        return

    for row in board:
        print(row)

n_queens(5)


[1, 0, 0, 0, 0]
[0, 0, 0, 1, 0]
[0, 1, 0, 0, 0]
[0, 0, 0, 0, 1]
[0, 0, 1, 0, 0]
