In [2]:
import torch

In [17]:
tensor = torch.tensor([
    [1, 2, 10],
    [1, 3, 20],
    [2, 4, 30],
    [2, 5, 40],
    [3, 6, 50],
    [3, 7, 60]
])
tensor_1 = tensor.unsqueeze(dim=1)
tensor_2 = tensor.unsqueeze(dim=0)
print(tensor_1.shape , tensor_2.shape)


torch.Size([6, 1, 3]) torch.Size([1, 6, 3])


In [18]:
(tensor_2 - tensor_1).shape

torch.Size([6, 6, 3])

In [15]:
tensor2 = torch.tensor([1,2,3,4,5,6])
tensor2 = tensor2.unsqueeze(dim=1)
tensor - tensor2

tensor([[ 0,  1,  9],
        [-1,  1, 18],
        [-1,  1, 27],
        [-2,  1, 36],
        [-2,  1, 45],
        [-3,  1, 54]])

In [3]:
column_to_group_by = tensor[:, 0]

In [6]:
column_to_group_by

tensor([1, 1, 2, 2, 3, 3])

In [14]:
torch.unique(column_to_group_by).size(0)

3

In [7]:
sum_tensor = torch.zeros(torch.unique(column_to_group_by).size(0))

for i, group_key in enumerate(torch.unique(column_to_group_by)):
    group_sum = tensor[column_to_group_by == group_key][:, 1].sum()
    sum_tensor[i] = group_sum

In [8]:
sum_tensor

tensor([ 5.,  9., 13.])

In [1]:
arr_1 = [1,2,3,4]
arr_2 = [3,4,5,6]
for k,v in zip(arr_1,arr_2):
    print(k,v)

1 3
2 4
3 5
4 6


In [5]:
def func_1(b:int):
    def func(a):

        a+=1
    func(a)
    return a,b

a = 4
b =5
func_1(b)

(4, 5)